# Generated by Django 4.0.2 on 2023-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name_plural': '5. Assessments'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': '3. Modules'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': '4. Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '6. Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '2. Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1. Teacher'},
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_lesson',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not yet started', 'Not yet started')], default='Not yet started', max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='unit_of_competency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
