# Generated by Django 4.0.2 on 2023-03-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0002_alter_assessment_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emodule.module')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('gdrive_link', models.URLField(verbose_name='Google Drive Link')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emodule.module')),
            ],
        ),
    ]
