# Generated by Django 4.0.2 on 2023-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0005_assessment_direction_quiz_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_quiz_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
