# Generated by Django 4.0.2 on 2023-03-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0006_module_date_quiz_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='module',
        ),
        migrations.AddField(
            model_name='assessment',
            name='quarter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emodule.quarter'),
            preserve_default=False,
        ),
    ]
