# Generated by Django 4.0.2 on 2023-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0007_remove_assessment_module_assessment_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='date_assessment_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarter',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not yet started', 'Not yet started')], default='Not yet started', max_length=200),
        ),
    ]
