# Generated by Django 4.0.2 on 2023-03-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0011_studentquizresult_studentquizquestionanswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassessmentresult',
            options={'get_latest_by': '-group'},
        ),
        migrations.AlterModelOptions(
            name='studentquizresult',
            options={'get_latest_by': '-group'},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='student_answer',
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='student_correct',
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_quiz_taken',
        ),
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='date_assessment_taken',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='student_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='student_correct',
        ),
    ]
