# Generated by Django 4.0.2 on 2023-03-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0012_alter_studentassessmentresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='seqno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
