# Generated by Django 4.0.2 on 2023-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodule', '0013_module_seqno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['seqno'], 'verbose_name_plural': '3. Modules'},
        ),
        migrations.AddField(
            model_name='performancetask',
            name='direction',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
